import React, { useEffect, useState } from 'react';
import { api } from '../../services/api';

type Allocation = { allocation_id: string; course_code: string; course_name: string; section_name: string };
type Defaulter = { student_id: string; institutional_id: string; full_name: string; attended_lectures: number; conducted_lectures: number; attendance_percentage: number };
type Trend = { lecture_id: string; starts_at: string; recorded: number; attended: number; attendance_percentage: number };

export const FacultyAnalyticsView: React.FC = () => {
  const [allocations, setAllocations] = useState<Allocation[]>([]); const [allocation, setAllocation] = useState('');
  const [threshold, setThreshold] = useState(75); const [rows, setRows] = useState<Defaulter[]>([]); const [trend, setTrend] = useState<Trend[]>([]);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [analyticsLoading, setAnalyticsLoading] = useState(false);
  useEffect(() => { api<Allocation[]>('/api/faculty/analytics/allocations').then((list) => { setAllocations(list); setAllocation(list[0]?.allocation_id || ''); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!allocation) { setRows([]); setTrend([]); return; } let active = true; setAnalyticsLoading(true); setError(''); Promise.all([
    api<Defaulter[]>(`/api/faculty/analytics/defaulters?allocation_id=${encodeURIComponent(allocation)}&threshold=${threshold}`),
    api<Trend[]>(`/api/faculty/analytics/trend?allocation_id=${encodeURIComponent(allocation)}`),
  ]).then(([defaulters, history]) => { if (active) { setRows(defaulters); setTrend(history); } }).catch((e) => { if (active) setError(e.message); }).finally(() => { if (active) setAnalyticsLoading(false); }); return () => { active = false; }; }, [allocation, threshold]);
  const selected = allocations.find((item) => item.allocation_id === allocation);
  return <div className="mx-auto w-full max-w-6xl space-y-5"><header><p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-dark">Faculty · live analytics</p><h1 className="text-2xl font-semibold text-slate-900">Course attendance</h1><p className="mt-1 text-sm text-slate-600">Review lecture trends and students below the selected threshold.</p></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <section className="flex flex-wrap items-end gap-4 rounded-2xl border bg-white p-5"><label className="min-w-64 flex-1 text-sm font-medium">Assigned course and section<select disabled={loading || !allocations.length} value={allocation} onChange={(e) => setAllocation(e.target.value)} className="mt-1.5 w-full rounded-lg border p-2.5"><option value="">{allocations.length ? 'Choose allocation' : 'No allocations available'}</option>{allocations.map((item) => <option key={item.allocation_id} value={item.allocation_id}>{item.course_code} · {item.course_name} — {item.section_name}</option>)}</select></label><label className="text-sm font-medium">Defaulter threshold (%)<input type="number" min="0" max="100" value={threshold} onChange={(e) => setThreshold(Math.max(0, Math.min(100, Number(e.target.value))))} className="mt-1.5 block w-40 rounded-lg border p-2.5"/></label></section>
    {selected && <p className="text-sm font-medium text-slate-700">{selected.course_code} · {selected.course_name}<span className="ml-2 text-slate-500">{selected.section_name}</span></p>}
    <section className="rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-sm font-semibold">Attendance by lecture</h2><p className="mt-1 text-xs text-slate-500">Recorded present or late marks divided by recorded attendance entries.</p></div>{analyticsLoading ? <p className="p-6 text-sm text-slate-500">Loading lecture trend…</p> : trend.length ? <div className="space-y-3 p-5">{trend.map((item) => <div key={item.lecture_id} className="grid grid-cols-[110px_1fr_80px] items-center gap-3 text-xs"><time className="text-slate-600">{new Date(item.starts_at).toLocaleDateString()}</time><div className="h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(0, Math.min(100, item.attendance_percentage))}%` }}/></div><span className="text-right font-mono">{item.attendance_percentage}% <span className="text-slate-500">({item.recorded})</span></span></div>)}</div> : <p className="p-6 text-sm text-slate-500">No lecture attendance has been recorded for this allocation.</p>}</section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-sm font-semibold">Students below {threshold}%</h2><p className="mt-1 text-xs text-slate-500">{rows.length} student{rows.length === 1 ? '' : 's'}</p></div>{analyticsLoading ? <p className="p-6 text-sm text-slate-500">Loading defaulters…</p> : rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="px-5 py-3">Student</th><th className="px-4 py-3">Attendance</th><th className="px-5 py-3">Rate</th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.student_id}><td className="px-5 py-3"><span className="block font-medium">{row.full_name}</span><span className="font-mono text-xs text-slate-500">{row.institutional_id}</span></td><td className="px-4 py-3">{row.attended_lectures} / {row.conducted_lectures}</td><td className="px-5 py-3 font-mono font-semibold">{row.attendance_percentage.toFixed(1)}%</td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-slate-500">No students are below this threshold.</p>}</section>
  </div>;
};
