import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Plus, Search } from 'lucide-react';
import { api, type ApiError } from '../../services/api';
import { useApp } from '../../context/AppContext';
type Request = { id: string; lecture_id: string | null; request_type: 'LEAVE' | 'REGULARIZATION'; status: 'PENDING' | 'APPROVED' | 'REJECTED'; reason: string; created_at: string; review_reason: string | null };
type Filter = 'all' | 'PENDING' | 'APPROVED' | 'REJECTED';
export const RegularizationListView: React.FC = () => {
  const { setSelectedRequestId, setCurrentRoute } = useApp(); const [items, setItems] = useState<Request[]>([]); const [status, setStatus] = useState<Filter>('all'); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { api<Request[]>('/api/student/requests').then(setItems).catch((e: ApiError) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => items.filter((item) => (status === 'all' || item.status === status) && `${item.id} ${item.reason} ${item.request_type}`.toLowerCase().includes(search.trim().toLowerCase())), [items, status, search]);
  return <div className="mx-auto w-full max-w-6xl space-y-5"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-dark">Student · live API</p><h1 className="text-2xl font-semibold tracking-tight text-slate-900">Attendance review requests</h1><p className="mt-1 text-sm text-slate-600">Review your submitted leave and regularization requests.</p></div><button onClick={() => setCurrentRoute('regularization-form')} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>New request</button></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div className="flex gap-1">{(['all','PENDING','APPROVED','REJECTED'] as Filter[]).map((value) => <button key={value} aria-pressed={status === value} onClick={() => setStatus(value)} className={`rounded-lg px-3 py-2 text-xs ${status === value ? 'bg-primary-container text-primary-dark' : 'text-slate-600'}`}>{value === 'all' ? 'All' : value}</button>)}</div><label className="relative block"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search requests" className="rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm"/></label></div>
      {loading ? <p className="p-6 text-sm text-slate-500">Loading requests…</p> : visible.length ? <ul className="divide-y divide-slate-100">{visible.map((item) => <li key={item.id}><button onClick={() => { setSelectedRequestId(item.id); setCurrentRoute('regularization-detail'); }} className="flex w-full items-start justify-between gap-4 p-4 text-left hover:bg-slate-50 sm:px-5"><span><span className="block font-mono text-xs text-slate-500">{item.id}</span><span className="mt-1 block text-sm font-medium text-slate-900">{item.request_type} · {new Date(item.created_at).toLocaleString()}</span><span className="mt-1 block text-sm text-slate-600">{item.reason}</span></span><span className="flex shrink-0 items-center gap-2 text-xs font-semibold">{item.status}<ArrowRight size={15}/></span></button></li>)}</ul> : <p className="p-8 text-center text-sm text-slate-500">No matching requests.</p>}
    </section></div>;
};
