import React, { useEffect, useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { api, jsonBody } from '../../services/api';
type Lecture = { lecture_id: string; course_code: string; course_name: string; starts_at: string; status: string | null };
export const RegularizationFormView: React.FC = () => {
  const { setCurrentRoute, setSelectedRequestId } = useApp();
  const [lectures, setLectures] = useState<Lecture[]>([]); const [type, setType] = useState<'LEAVE'|'REGULARIZATION'>('REGULARIZATION'); const [lectureId, setLectureId] = useState(''); const [reason, setReason] = useState(''); const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api<Lecture[]>('/api/student/attendance/history?limit=500').then((rows) => { setLectures(rows.filter((row) => type === 'LEAVE' || row.status === 'ABSENT' || row.status === 'EXCUSED')); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [type]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSaving(true); try { const created = await api<{id:string}>('/api/student/requests', { method:'POST', body:jsonBody({ lecture_id: lectureId, request_type:type, reason:reason.trim() }) }); if (file) { const form = new FormData(); form.append('file', file); await api(`/api/student/requests/${created.id}/documents`, { method:'POST', body:form }); } setSelectedRequestId(created.id); setCurrentRoute('regularization-detail'); } catch (e) { setError(e instanceof Error ? e.message : 'Request could not be submitted.'); } finally { setSaving(false); } };
  return <div className="mx-auto w-full max-w-3xl space-y-6"><button onClick={() => setCurrentRoute('leave-medical-slips')} className="inline-flex items-center gap-2 text-sm font-medium text-slate-600"><ArrowLeft size={16}/>Back to requests</button><header><p className="text-xs font-medium uppercase tracking-wide text-primary-dark">Student · live API</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Request attendance review</h1><p className="mt-2 text-sm text-slate-600">Submit a request for a lecture in your assigned section. Supporting documents are optional.</p></header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><label className="block space-y-1.5 text-sm font-medium text-slate-700">Request type<select value={type} onChange={(event) => setType(event.target.value as typeof type)} className="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 font-normal"><option value="REGULARIZATION">Attendance regularization</option><option value="LEAVE">Leave</option></select></label>
      <label className="block space-y-1.5 text-sm font-medium text-slate-700">Lecture<select required disabled={loading} value={lectureId} onChange={(event) => setLectureId(event.target.value)} className="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 font-normal"><option value="">{loading ? 'Loading lectures…' : lectures.length ? 'Choose lecture' : 'No eligible lectures found'}</option>{lectures.map((lecture) => <option key={lecture.lecture_id} value={lecture.lecture_id}>{lecture.course_code} · {lecture.course_name} · {new Date(lecture.starts_at).toLocaleString()} · {lecture.status || 'unmarked'}</option>)}</select></label>
      <label className="block space-y-1.5 text-sm font-medium text-slate-700">Reason<textarea required minLength={10} maxLength={2000} rows={6} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain your request (10–2000 characters)." className="block w-full resize-y rounded-lg border border-slate-300 px-3 py-2.5 font-normal"/><span className="block text-right text-xs font-normal text-slate-500">{reason.length}/2000</span></label>
      <label className="block space-y-1.5 text-sm font-medium text-slate-700">Supporting document (PDF, PNG, JPEG)<input type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0] || null)} className="block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-normal"/><span className="block text-xs font-normal text-slate-500">Upload occurs after request creation. If upload fails, the request remains submitted and can be reopened to attach documentation.</span></label>
      <div className="flex justify-end gap-3"><button type="button" onClick={() => setCurrentRoute('leave-medical-slips')} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</button><button disabled={saving || loading || !lectureId || reason.trim().length < 10} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?'Submitting…':'Submit request'}</button></div>
    </form></div>;
};
