import React, { useEffect, useState } from 'react';
import { ArrowLeft, Upload } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
type Request = { id: string; student_id: string; lecture_id: string | null; request_type: string; status: string; reason: string; reviewed_by: string | null; review_reason: string | null; reviewed_at: string | null; created_at: string };
type Document = { id: string; original_filename: string; content_type: string; size_bytes: number };
export const RegularizationDetailView: React.FC = () => {
  const { selectedRequestId, currentRole, setCurrentRoute } = useApp(); const [item, setItem] = useState<Request|null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [file, setFile] = useState<File|null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const base = currentRole === 'faculty' ? '/api/faculty/requests' : '/api/student/requests';
  useEffect(() => { if (!selectedRequestId) return; api<Request>(`${base}/${selectedRequestId}`).then(setItem).catch((e) => setError(e.message)); api<Document[]>(`${base}/${selectedRequestId}/documents`).then(setDocuments).catch(() => setDocuments([])); }, [selectedRequestId, base]);
  const back = currentRole === 'faculty' ? 'faculty-approvals' : 'leave-medical-slips';
  const upload = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !item) return; setBusy(true); setError(''); const form = new FormData(); form.append('file', file); try { await api(`/api/student/requests/${item.id}/documents`, { method:'POST', body:form }); setDocuments(await api<Document[]>(`/api/student/requests/${item.id}/documents`)); setFile(null); } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed.'); } finally { setBusy(false); } };
  if (!selectedRequestId) return <div className="p-8 text-center text-sm">Choose a request first.</div>;
  return <div className="mx-auto w-full max-w-4xl space-y-5"><button onClick={() => setCurrentRoute(back)} className="inline-flex items-center gap-2 text-sm font-medium text-slate-600"><ArrowLeft size={16}/>Back to requests</button>{error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}{!item ? <p className="text-sm text-slate-500">Loading request…</p> : <><header><p className="text-xs font-medium uppercase tracking-wide text-primary-dark">{currentRole} · live API</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Request details</h1></header><section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Request ID</dt><dd className="mt-1 break-all font-mono text-sm">{item.id}</dd></div><div><dt className="text-xs text-slate-500">Status</dt><dd className="mt-1 text-sm font-semibold">{item.status}</dd></div><div><dt className="text-xs text-slate-500">Type</dt><dd className="mt-1 text-sm">{item.request_type}</dd></div><div><dt className="text-xs text-slate-500">Submitted</dt><dd className="mt-1 text-sm">{new Date(item.created_at).toLocaleString()}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-slate-500">Reason</dt><dd className="mt-1 whitespace-pre-wrap text-sm leading-6">{item.reason}</dd></div>{item.review_reason && <div className="sm:col-span-2"><dt className="text-xs text-slate-500">Review note</dt><dd className="mt-1 text-sm">{item.review_reason}</dd></div>}</dl></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Supporting documents</h2>{documents.length ? <ul className="mt-3 space-y-2">{documents.map((doc) => <li key={doc.id} className="text-sm text-slate-700">{doc.original_filename} · {(doc.size_bytes/1024).toFixed(1)} KB</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No documents attached.</p>}{currentRole === 'student' && item.status === 'PENDING' && <form onSubmit={upload} className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs font-medium text-slate-600">Add PDF, PNG, or JPEG<input required type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-1 block text-sm"/></label><button disabled={busy || !file} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Upload size={14}/>{busy?'Uploading…':'Upload'}</button></form>}</section></>}</div>;
};
