import React, { useEffect, useMemo, useState } from 'react';
import { api, jsonBody } from '../../services/api';
import { useApp } from '../../context/AppContext';

type Field = { key: string; label: string; type?: 'text' | 'number' | 'date' | 'time' | 'uuid' | 'boolean'; required?: boolean; min?: number; max?: number };
type ResourceConfig = { title: string; path: string; create: Field[]; update: Field[] };
const resources: Record<string, ResourceConfig> = {
  'admin-departments': { title: 'Departments', path: 'departments', create: [{ key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }], update: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-academic-years': { title: 'Academic years', path: 'academic-years', create: [{ key: 'name', label: 'Name', required: true }, { key: 'starts_on', label: 'Starts on', type: 'date', required: true }, { key: 'ends_on', label: 'Ends on', type: 'date', required: true }], update: [{ key: 'name', label: 'Name' }, { key: 'starts_on', label: 'Starts on', type: 'date' }, { key: 'ends_on', label: 'Ends on', type: 'date' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-semesters': { title: 'Semesters', path: 'semesters', create: [{ key: 'academic_year_id', label: 'Academic year ID', type: 'uuid', required: true }, { key: 'number', label: 'Semester number', type: 'number', required: true, min: 1, max: 12 }, { key: 'starts_on', label: 'Starts on', type: 'date', required: true }, { key: 'ends_on', label: 'Ends on', type: 'date', required: true }], update: [{ key: 'number', label: 'Semester number', type: 'number' }, { key: 'starts_on', label: 'Starts on', type: 'date' }, { key: 'ends_on', label: 'Ends on', type: 'date' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-sections': { title: 'Sections', path: 'sections', create: [{ key: 'department_id', label: 'Department ID', type: 'uuid', required: true }, { key: 'academic_year_id', label: 'Academic year ID', type: 'uuid', required: true }, { key: 'name', label: 'Name', required: true }], update: [{ key: 'name', label: 'Name' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-courses': { title: 'Courses', path: 'courses', create: [{ key: 'department_id', label: 'Department ID', type: 'uuid', required: true }, { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'credits', label: 'Credits', type: 'number', min: 0, max: 30 }], update: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'credits', label: 'Credits', type: 'number', min: 0, max: 30 }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-classrooms': { title: 'Classrooms', path: 'classrooms', create: [{ key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'capacity', label: 'Capacity', type: 'number', min: 1 }], update: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'capacity', label: 'Capacity', type: 'number', min: 1 }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-allocations': { title: 'Faculty allocations', path: 'allocations', create: [{ key: 'course_id', label: 'Course ID', type: 'uuid', required: true }, { key: 'semester_id', label: 'Semester ID', type: 'uuid', required: true }, { key: 'section_id', label: 'Section ID', type: 'uuid', required: true }, { key: 'faculty_id', label: 'Faculty user ID', type: 'uuid', required: true }], update: [{ key: 'faculty_id', label: 'Faculty user ID', type: 'uuid' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
  'admin-timetable': { title: 'Timetable', path: 'timetable', create: [{ key: 'allocation_id', label: 'Allocation ID', type: 'uuid', required: true }, { key: 'classroom_id', label: 'Classroom ID', type: 'uuid', required: true }, { key: 'weekday', label: 'Weekday (0=Mon)', type: 'number', min: 0, max: 6, required: true }, { key: 'starts_at', label: 'Starts at', type: 'time', required: true }, { key: 'ends_at', label: 'Ends at', type: 'time', required: true }, { key: 'effective_from', label: 'Effective from', type: 'date', required: true }, { key: 'effective_until', label: 'Effective until', type: 'date' }], update: [{ key: 'allocation_id', label: 'Allocation ID', type: 'uuid' }, { key: 'classroom_id', label: 'Classroom ID', type: 'uuid' }, { key: 'weekday', label: 'Weekday', type: 'number', min: 0, max: 6 }, { key: 'starts_at', label: 'Starts at', type: 'time' }, { key: 'ends_at', label: 'Ends at', type: 'time' }, { key: 'effective_from', label: 'Effective from', type: 'date' }, { key: 'effective_until', label: 'Effective until', type: 'date' }, { key: 'is_active', label: 'Active', type: 'boolean' }] },
};
const inputClass = 'w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-primary';

export const AdminResourceManager: React.FC<{ route: string }> = ({ route }) => {
  const config = resources[route];
  const { addToast } = useApp();
  const [rows, setRows] = useState<Record<string, unknown>[]>([]);
  const [values, setValues] = useState<Record<string, string | boolean>>({});
  const [selected, setSelected] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const fields = selected ? config.update : config.create;
  const labelByKey = useMemo(() => new Map(fields.map((field) => [field.key, field.label])), [fields]);
  const load = async () => { setLoading(true); setError(''); try { setRows(await api<Record<string, unknown>[]>(`/api/admin/${config.path}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load records.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [route]);
  const choose = (row: Record<string, unknown>) => { setSelected(row); const next: Record<string, string | boolean> = {}; config.update.forEach((field) => { const value = row[field.key]; next[field.key] = typeof value === 'boolean' ? value : value == null ? '' : field.type === 'time' ? String(value).slice(0, 5) : String(value); }); setValues(next); };
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true); setError('');
    const payload: Record<string, unknown> = {};
    fields.forEach((field) => { const raw = values[field.key]; if (raw === '' || raw === undefined) return; payload[field.key] = field.type === 'number' ? Number(raw) : field.type === 'boolean' ? raw === true || raw === 'true' : raw; });
    try {
      if (selected) await api(`/api/admin/${config.path}/${selected.id}`, { method: 'PATCH', body: jsonBody(payload) });
      else await api(`/api/admin/${config.path}`, { method: 'POST', body: jsonBody(payload) });
      setSelected(null); setValues({}); await load(); addToast({ type: 'success', message: `${config.title} ${selected ? 'updated' : 'created'}.` });
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed.'); }
    finally { setSaving(false); }
  };
  return <div className="mx-auto w-full max-w-6xl space-y-6">
    <header><p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-dark">Administrator · live API</p><h1 className="text-2xl font-semibold tracking-tight text-slate-900">{config.title}</h1><p className="mt-1 text-sm text-slate-600">Changes are validated and saved by the AMS API. Foreign keys require the corresponding record UUID.</p></header>
    {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{selected ? `Edit ${String(selected.id).slice(0, 8)}` : `Create ${config.title.slice(0, -1)}`}</h2>{selected && <button type="button" onClick={() => { setSelected(null); setValues({}); }} className="text-xs text-primary-dark">Cancel edit</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label key={field.key} className="space-y-1 text-xs font-medium text-slate-600">{field.label}{field.type === 'boolean' ? <select className={inputClass} value={String(values[field.key] ?? false)} onChange={(event) => setValues({ ...values, [field.key]: event.target.value === 'true' })}><option value="true">Active</option><option value="false">Inactive</option></select> : <input className={inputClass} type={field.type === 'uuid' ? 'text' : field.type || 'text'} inputMode={field.type === 'uuid' ? 'text' : undefined} placeholder={field.type === 'uuid' ? 'UUID' : undefined} required={!selected && field.required} min={field.min} max={field.max} value={String(values[field.key] ?? '')} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} />}</label>)}</div><button disabled={saving} className="mt-4 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving…' : selected ? 'Save changes' : 'Create record'}</button></form>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold">Records</h2></div>{loading ? <p className="p-6 text-sm text-slate-500">Loading records…</p> : rows.length === 0 ? <p className="p-6 text-sm text-slate-500">No records yet.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs text-slate-500"><th className="px-5 py-3">ID</th>{fields.slice(0, 4).map((field) => <th key={field.key} className="px-3 py-3">{labelByKey.get(field.key)}</th>)}<th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={String(row.id)}><td className="px-5 py-3 font-mono text-[11px] text-slate-500">{String(row.id).slice(0, 8)}</td>{fields.slice(0, 4).map((field) => <td key={field.key} className="px-3 py-3 text-slate-700">{String(row[field.key] ?? '—')}</td>)}<td className="px-5 py-3"><button type="button" onClick={() => choose(row)} className="text-sm font-medium text-primary-dark hover:underline">Edit</button></td></tr>)}</tbody></table></div>}</section>
  </div>;
};
