import React, { useEffect, useState } from 'react';
import { Save, Settings2 } from 'lucide-react';
import { api, jsonBody } from '../../services/api';

export const AdminGovernanceView: React.FC = () => {
  const [threshold, setThreshold] = useState(75); const [email, setEmail] = useState(false); const [sms, setSms] = useState(false);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { Promise.all([api<{ attendance_threshold: number }>('/api/admin/settings/attendance-threshold'), api<{ email_enabled: boolean; sms_enabled: boolean }>('/api/admin/settings/notifications')]).then(([attendance, notification]) => { setThreshold(attendance.attendance_threshold); setEmail(notification.email_enabled); setSms(notification.sms_enabled); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Settings could not be loaded.')).finally(() => setLoading(false)); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { await api('/api/admin/settings/attendance-threshold', { method: 'PUT', body: jsonBody({ attendance_threshold: threshold }) }); await api('/api/admin/settings/notifications', { method: 'PUT', body: jsonBody({ email_enabled: email, sms_enabled: sms }) }); setMessage('Settings saved.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Settings could not be saved.'); } finally { setSaving(false); } };
  return <div className="mx-auto w-full max-w-4xl space-y-5"><header><p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-dark">Administrator · live API</p><h1 className="text-2xl font-semibold tracking-tight text-slate-900">System settings</h1><p className="mt-1 text-sm text-slate-600">Configure the attendance threshold and delivery channels. The API records changes in its audit log.</p></header>
    {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}{message && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</div>}
    <form onSubmit={save} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary-container text-primary-dark"><Settings2 size={17}/></span><div><h2 className="text-sm font-semibold text-slate-900">Attendance threshold</h2><p className="mt-1 text-xs leading-5 text-slate-500">Used as the default eligibility target in attendance analytics.</p></div></div>
      <label className="block max-w-sm text-sm font-medium text-slate-800">Threshold (%)<input type="number" inputMode="decimal" min="0" max="100" step="0.1" required value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-mono text-sm outline-none focus:border-primary" /></label>
      <fieldset><legend className="text-sm font-semibold text-slate-900">Notification delivery</legend><p className="mt-1 text-xs text-slate-500">A channel can only be enabled after its provider is configured on the backend.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" checked={email} onChange={(event) => setEmail(event.target.checked)} />Email delivery</label><label className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" checked={sms} onChange={(event) => setSms(event.target.checked)} />SMS delivery</label></div></fieldset>
      <button disabled={loading || saving} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Save size={15}/>{loading ? 'Loading…' : saving ? 'Saving…' : 'Save settings'}</button>
    </form></div>;
};
